import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { NavComponent } from "./_components/nav/nav.component";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: "./favicon.ico"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavComponent />
      {children}</body>
    </html>
  );
}
